CREATE TABLE PRODUCT_MASTER23
(
PRODUCTNO	Varchar(6),
DESCRIPTION	Varchar(15),
PROFITPERCENT	Double(4,2),
`UNIT MEASURE`	Varchar(10),
`QTYONHAND`	Int,	
`REORDERL VL`	Int,
SELLPRICE	Double(8,2),
COSTPRICE	double(8,2)
);
CREATE TABLE SALESMAN_MASTER23
(
SALESMANNO	Varchar(6),
SALESMANNAME	Varchar(20),
`ADDRESS 1` Varchar(30),
`ADDRESS 2`	Varchar(30),
CITY	Varchar(20),
PINCODE	Int,
STATE	Varchar(20),
SALAMT	INT,
TGTTOGET	DOUBLE,
YTDSALES	Double(6,2),
REMARKS	Varchar(60)
);